"""
Tests for offdevice/sensor/bme280_ref.py -- the sensor-path parity reference.

What can be pinned without hardware: the trim assembly rules (incl. the signed
H4/H5 nibble packing), C-truncating division, the two datasheet-quoted example
conversions, and the parser+comparator loop closed over a synthetic console
dump generated by the reference itself. The real validation -- reference vs
chip -- is the parity gate run on a live self-test capture; a pinned full
vector here is a regression tripwire for accidental edits, not proof of
correctness.
"""

from __future__ import annotations

import dataclasses

import pytest

from offdevice.sensor.bme280_ref import (
    Trim,
    _truncdiv,
    check_parity,
    compensate_h_int32,
    compensate_p_int64,
    compensate_t_int32,
    parse_selftest,
    to_spec_scales,
    unpack_trim,
)

# A plausible trim set (mid-range values of the kind real chips carry), used
# for self-consistency tests. NOT from a real chip.
TRIM = Trim(T1=28485, T2=26735, T3=50,
            P1=36738, P2=-10635, P3=3024, P4=7980, P5=-160,
            P6=-7, P7=15500, P8=-14600, P9=6000,
            H1=75, H2=376, H3=0, H4=297, H5=50, H6=30)


def _trim_to_calib(t: Trim) -> tuple[bytes, bytes]:
    """Inverse of unpack_trim: encode trim words into the raw calib blobs."""
    def u16(v: int) -> bytes:
        return bytes(((v & 0xFFFF) & 0xFF, (v & 0xFFFF) >> 8))

    a = b"".join(u16(v) for v in (t.T1, t.T2, t.T3, t.P1, t.P2, t.P3,
                                  t.P4, t.P5, t.P6, t.P7, t.P8, t.P9))
    a += bytes((0x00, t.H1))                      # 0xA0 skipped byte, then H1
    e4 = (t.H4 >> 4) & 0xFF                       # H4[11:4]
    e5 = ((t.H5 & 0x0F) << 4) | (t.H4 & 0x0F)     # H5[3:0] | H4[3:0]
    e6 = (t.H5 >> 4) & 0xFF                       # H5[11:4]
    b = u16(t.H2) + bytes((t.H3, e4, e5, e6, t.H6 & 0xFF))
    return a, b


# ---- trim assembly -----------------------------------------------------------

def test_unpack_trim_roundtrip():
    a, b = _trim_to_calib(TRIM)
    assert unpack_trim(a, b) == TRIM


def test_unpack_trim_negative_h4_h5():
    neg = dataclasses.replace(TRIM, H4=-1500, H5=-2048)
    a, b = _trim_to_calib(neg)
    got = unpack_trim(a, b)
    assert got.H4 == -1500
    assert got.H5 == -2048


def test_unpack_trim_rejects_wrong_sizes():
    with pytest.raises(ValueError):
        unpack_trim(b"\x00" * 25, b"\x00" * 7)


# ---- C division semantics ------------------------------------------------------

def test_truncdiv_matches_c_not_python():
    assert _truncdiv(-7, 2) == -3          # C truncates; Python -7 // 2 == -4
    assert _truncdiv(7, -2) == -3
    assert _truncdiv(-7, -2) == 3
    assert _truncdiv(7, 2) == 3


# ---- datasheet-quoted conversions ---------------------------------------------

def test_spec_scale_press_matches_datasheet_example():
    # Datasheet 4.2.3: P output 24674867 represents 24674867/256 = 96386.2 Pa.
    _, _, press = to_spec_scales(0, 24674867, 0)
    assert press == 96386


def test_spec_scale_hum_matches_datasheet_example():
    # Datasheet 4.2.3: H output 47445 represents 47445/1024 = 46.333 %RH.
    _, hum, _ = to_spec_scales(0, 0, 47445)
    assert hum == 4633


def test_spec_scale_temp_passthrough():
    temp, _, _ = to_spec_scales(5123, 0, 0)   # "5123 equals 51.23 DegC"
    assert temp == 5123


# ---- pinned full vector (regression tripwire) ----------------------------------

def test_pinned_vector_regression():
    """Characterization pin: frozen reference outputs; they move ONLY if the math is edited."""
    t, t_fine = compensate_t_int32(519888, TRIM)
    p = compensate_p_int64(415148, t_fine, TRIM)
    h = compensate_h_int32(30040, t_fine, TRIM)
    assert (t, t_fine) == (2044, 104653)
    assert p == 21822562
    assert h == 64516
    assert to_spec_scales(t, p, h) == (2044, 6300, 85244)


# ---- parser + comparator closed loop --------------------------------------------

def _fake_console(trim: Trim, adc_vectors: list[tuple[int, int, int]]) -> str:
    """Render a self-test console dump whose numbers come from this reference."""
    a, b = _trim_to_calib(trim)
    lines = [
        f"[BME] calibA {a.hex().upper()}",
        f"[BME] calibB {b.hex().upper()}",
        f"[BME] trimT T1={trim.T1} T2={trim.T2} T3={trim.T3}",
        f"[BME] trimP P1={trim.P1} P2={trim.P2} P3={trim.P3} P4={trim.P4} P5={trim.P5}"
        f" P6={trim.P6} P7={trim.P7} P8={trim.P8} P9={trim.P9}",
        f"[BME] trimH H1={trim.H1} H2={trim.H2} H3={trim.H3} H4={trim.H4} H5={trim.H5} H6={trim.H6}",
    ]
    for n, (ut, up, uh) in enumerate(adc_vectors, start=1):
        t, t_fine = compensate_t_int32(ut, trim)
        p = compensate_p_int64(up, t_fine, trim)
        h = compensate_h_int32(uh, t_fine, trim)
        temp, hum, press = to_spec_scales(t, p, h)
        lines += [
            f"[BME] vec{n} raw ut={ut} up={up} uh={uh}",
            f"[BME] vec{n} cmp tfine={t_fine} T={t} P={p} H={h}",
            f"[BME] vec{n} rec temp={temp} hum={hum} press={press}",
        ]
    return "\r\n".join(lines) + "\r\n"


ADC_VECTORS = [(519888, 415148, 30040), (524288, 420000, 28000), (500000, 400000, 33000)]


def test_parse_and_parity_pass_on_consistent_dump():
    dump = parse_selftest(_fake_console(TRIM, ADC_VECTORS))
    assert len(dump.vectors) == 3
    assert check_parity(dump) == []


def test_parity_fails_on_corrupted_compensation_value():
    text = _fake_console(TRIM, ADC_VECTORS)
    dump = parse_selftest(text)
    bad = text.replace(f"tfine={dump.vectors[0]['tfine']} ", f"tfine={dump.vectors[0]['tfine'] + 1} ", 1)
    fails = check_parity(parse_selftest(bad))
    assert any("vec1 tfine" in f for f in fails)


def test_parity_fails_on_bad_trim_assembly():
    text = _fake_console(TRIM, ADC_VECTORS)
    # Firmware claims a different H4 than its own calib bytes imply.
    bad = text.replace(f"H4={TRIM.H4} ", f"H4={TRIM.H4 + 1} ")
    fails = check_parity(parse_selftest(bad))
    assert any(f.startswith("trim H4") for f in fails)


def test_parse_rejects_missing_lines():
    with pytest.raises(ValueError):
        parse_selftest("[BME] selftest: begin\r\n")
