"""
Render the on-chip feature constants into the Secure firmware project.

Run from the repo root after any change to params.py or fixtures.py (both are
frozen contracts, so in practice: rarely and deliberately):

    python -m offdevice.features.gen_tables

Two GENERATED headers land in Secure/Core/Inc (the scanner's world; new
headers need no .project surgery, unlike .c files):

    nv_feat_tables.h   -- window, mel bank, DCT, chroma bank + pipeline constants
    nv_feat_fixture.h  -- the golden vector's exact 4096 input bytes (parity builds)

test_feat_tables.py fails loudly if the on-disk copies drift from a fresh
render, and proves the tables reproduce librosa before the chip ever sees them.
"""

import math
from pathlib import Path

import numpy as np
import numpy.typing as npt
import librosa
import scipy

from offdevice.features import params, tables
from offdevice.tests.fixtures import synthetic_nv_region

REPO_ROOT = Path(__file__).resolve().parents[2]
TARGET_DIR = REPO_ROOT / "firmware" / "memAcq" / "Secure" / "Core" / "Inc"
TABLES_TARGET = TARGET_DIR / "nv_feat_tables.h"
FIXTURE_TARGET = TARGET_DIR / "nv_feat_fixture.h"

_PER_LINE = 6        # float literals per line -- keeps the arrays diffable
_BYTES_PER_LINE = 16
_NAME_W = 22         # #define name column


def _c_float(value: float | np.floating) -> str:
    """A float32 as a C literal that parses back to the identical float32."""
    v = float(np.float32(value))
    if not math.isfinite(v):
        raise ValueError(f"non-finite value in table: {v!r}")
    text = f"{v:.9g}"   # 9 significant digits round-trip any float32
    if "." not in text and "e" not in text:
        text += ".0"    # "1" is an int literal; "1.0f" is the float
    return text + "f"


def _define(name: str, value: str, comment: str = "") -> str:
    line = f"#define {name:<{_NAME_W}}{value}"
    if comment:
        line = f"{line}   /* {comment} */"
    return line


def _chunk_lines(tokens: list[str], indent: str) -> list[str]:
    return [indent + ", ".join(tokens[i:i + _PER_LINE]) + ","
            for i in range(0, len(tokens), _PER_LINE)]


def _vector_block(name: str, dim: str, vec: npt.NDArray[np.float32]) -> list[str]:
    lines = [f"static const float {name}[{dim}] =", "{"]
    lines += _chunk_lines([_c_float(v) for v in vec], "    ")
    return lines + ["};"]


def _matrix_block(name: str, dims: str, matrix: npt.NDArray[np.float32]) -> list[str]:
    lines = [f"static const float {name}{dims} =", "{"]
    for row in matrix:
        lines.append("    {")
        lines += _chunk_lines([_c_float(v) for v in row], "        ")
        lines.append("    },")
    return lines + ["};"]


def render_tables_header() -> str:
    """The full nv_feat_tables.h text, derived from params.py via tables.py."""
    n_dims = params.N_BINS * params.N_FEATURES
    lines = [
        "/*",
        " * nv_feat_tables.h -- on-chip feature constants. GENERATED by",
        " * offdevice/features/gen_tables.py -- DO NOT EDIT; regenerate:",
        " *",
        " *     python -m offdevice.features.gen_tables",
        " *",
        f" * Tables computed by librosa {librosa.__version__} / scipy {scipy.__version__} -- the",
        " * pinned reference environment (offdevice/DATASET.md) that also produced the",
        " * golden vector, so the chip never re-derives a constant. The mel bank is",
        " * shared: params.py pins MFCC's internal bank == the standalone mel's, so",
        " * ONE bank feeds both.",
        " *",
        " * Pipeline these tables belong to (reference implementation:",
        " * offdevice/features/tables.py, extract_features_ref):",
        " *",
        " *   signal[4096]: each dump byte -> int16 -> * NVF_SIGNAL_SCALE",
        " *   33 frames of 512: frame t covers signal[t*NVF_HOP - NVF_PAD ..) with",
        " *       zeros outside the window (librosa center=True, zero padding)",
        " *   per frame: multiply by nvf_hann; real FFT; power[b] = re^2 + im^2",
        " *   mel_power = nvf_mel_bank @ power             (40 x 33)",
        " *   mel feature = per-band mean over frames",
        " *   dB = 10*log10(max(NVF_AMIN, mel_power));",
        " *       dB = max(dB, GLOBAL max - NVF_TOP_DB)    <- max over ALL 40x33",
        " *   mfcc = nvf_dct @ dB; feature = per-coefficient mean over frames",
        " *   chroma = nvf_chroma_bank @ power; each FRAME divided by its own peak",
        " *       (a peak below NVF_NORM_TINY divides by 1); per-bin mean over frames",
        " *   output, feature-major: [40 mfcc][40 mel][40 chroma] = NVF_N_DIMS",
        " *",
        " * The arrays are static: include from ONE translation unit only",
        " * (nv_features.c).",
        " */",
        "#ifndef NV_FEAT_TABLES_H",
        "#define NV_FEAT_TABLES_H",
        "",
        _define("NVF_WINDOW_BYTES", f"{params.WINDOW_BYTES}U", "the 4 KB NV region; 1 byte = 1 sample"),
        _define("NVF_N_FFT", f"{params.N_FFT}U"),
        _define("NVF_HOP", f"{params.HOP_LENGTH}U"),
        _define("NVF_N_FRAMES", f"{tables.N_FRAMES}U", "1 + WINDOW_BYTES/HOP (centered framing)"),
        _define("NVF_N_SPEC_BINS", f"{tables.N_SPEC_BINS}U", "N_FFT/2 + 1 real-FFT bins"),
        _define("NVF_PAD", f"{tables.PAD}U", "frame t starts at t*NVF_HOP - this"),
        _define("NVF_N_MELS", f"{params.N_MELS}U"),
        _define("NVF_N_MFCC", f"{params.N_MFCC}U"),
        _define("NVF_N_CHROMA", f"{params.N_CHROMA}U"),
        _define("NVF_N_DIMS", f"{n_dims}U", "the model's input vector"),
        _define("NVF_SIGNAL_SCALE", "(1.0f / 32768.0f)", "uint8 byte -> int16 -> * this"),
        _define("NVF_AMIN", _c_float(tables.AMIN), "power floor before log10"),
        _define("NVF_TOP_DB", _c_float(tables.TOP_DB), "dB clamp: GLOBAL max - this"),
        _define("NVF_NORM_TINY", _c_float(tables.NORM_TINY), "chroma peak below this: divide by 1"),
        "",
        "/* Periodic Hann, applied to every frame before its FFT. */",
    ]
    lines += _vector_block("nvf_hann", "NVF_N_FFT", tables.hann_window())
    lines += [
        "",
        "/* The ONE mel bank -- feeds the mel feature AND MFCC's dB + DCT path. */",
    ]
    lines += _matrix_block("nvf_mel_bank", "[NVF_N_MELS][NVF_N_SPEC_BINS]",
                           tables.mel_filterbank())
    lines += [
        "",
        "/* Orthonormal DCT rows: mfcc[k] = sum over n of nvf_dct[k][n] * dB[n]. */",
    ]
    lines += _matrix_block("nvf_dct", "[NVF_N_MFCC][NVF_N_MELS]", tables.dct_matrix())
    lines += [
        "",
        "/* Chroma bank at the frozen tuning of 0.0. */",
    ]
    lines += _matrix_block("nvf_chroma_bank", "[NVF_N_CHROMA][NVF_N_SPEC_BINS]",
                           tables.chroma_filterbank())
    lines += ["", "#endif /* NV_FEAT_TABLES_H */", ""]
    return "\n".join(lines)


def render_fixture_header() -> str:
    """The full nv_feat_fixture.h text -- the golden vector's exact input bytes."""
    data = synthetic_nv_region()
    lines = [
        "/*",
        " * nv_feat_fixture.h -- the golden vector's exact 4 KB input. GENERATED by",
        " * offdevice/features/gen_tables.py from offdevice/tests/fixtures.py --",
        " * DO NOT EDIT; regenerate: python -m offdevice.features.gen_tables",
        " *",
        " * Parity gate (a): feed these bytes through the on-chip feature chain and",
        " * compare the printed 120 outputs, on the laptop, against the committed",
        " * golden (offdevice/tests/golden/synthetic_features.npy). Parity builds",
        " * only -- nothing in the deploy build includes this.",
        " */",
        "#ifndef NV_FEAT_FIXTURE_H",
        "#define NV_FEAT_FIXTURE_H",
        "",
        "#include <stdint.h>",
        "",
        f"static const uint8_t nvf_fixture[{len(data)}] =",
        "{",
    ]
    for i in range(0, len(data), _BYTES_PER_LINE):
        chunk = data[i:i + _BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines += ["};", "", "#endif /* NV_FEAT_FIXTURE_H */", ""]
    return "\n".join(lines)


def main() -> None:
    """Render once; write both headers into the Secure project."""
    if not TARGET_DIR.is_dir():
        raise SystemExit(f"missing {TARGET_DIR} -- run from a full repo checkout")

    stats = (
        ("nvf_hann", tables.hann_window()),
        ("nvf_mel_bank", tables.mel_filterbank()),
        ("nvf_dct", tables.dct_matrix()),
        ("nvf_chroma_bank", tables.chroma_filterbank()),
    )
    total = 0
    for name, arr in stats:
        total += arr.size * 4
        print(f"[gen_tables] {name:<16} {arr.size:>6} floats  {arr.size * 4:>6} B  "
              f"min={arr.min():+.6e}  max={arr.max():+.6e}")
    print(f"[gen_tables] const tables total {total} B"
          f" + fixture {params.WINDOW_BYTES} B (parity builds only)")

    for target, text in ((TABLES_TARGET, render_tables_header()),
                         (FIXTURE_TARGET, render_fixture_header())):
        with target.open("w", encoding="ascii", newline="\n") as f:
            f.write(text)
        print(f"[gen_tables] wrote {target.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
