"""
Export a .tflite as an OSPI XIP weight blob + an attestation header.

The blob is flashed raw to the external OSPI chip at 0x90000000 (weights live
OUTSIDE the SHA-256-attested internal region). The header is compiled INTO the
attested internal image . It carries the blob's SHA-256 digest + length, so the
boot-time check (firmware ospi_hash.c) can prove the external weights are the
ones we shipped. An attacker who reflashes OSPI can't match the digest without
also tampering the internal image, which trips the existing static hash.


    python -m offdevice.cnn_quant.model.blob_export <model.tflite>
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path


def export_blob(tflite_path: Path, out_dir: Path | None = None):
    data = tflite_path.read_bytes()
    if data[4:8] != b"TFL3":
        raise SystemExit(f"{tflite_path} is not a TFLite flatbuffer (no TFL3 magic)")

    out_dir = out_dir or tflite_path.parent / "ospi"
    out_dir.mkdir(parents=True, exist_ok=True)

    # pad to a 16-byte boundary: TFLM parses in place from XIP, and OSPI page
    # programming is doubleword-aligned. Padding is zeros (benign to the parser).
    pad = (-len(data)) % 16
    blob = data + b"\x00" * pad
    digest = hashlib.sha256(blob).digest()

    blob_path = out_dir / (tflite_path.stem + ".blob")
    blob_path.write_bytes(blob)

    header = out_dir / "ospi_blob_attest.h"
    hexrows = "\n".join(
        "  " + " ".join(f"0x{b:02x}," for b in digest[i:i + 8])
        for i in range(0, len(digest), 8)
    )
    header.write_text(f"""// GENERATED by blob_export.py - do not edit.
// Attestation for the OSPI XIP weight blob at 0x90000000.
// blob: {blob_path.name}  ({len(blob)} bytes, 16-aligned)
#ifndef OSPI_BLOB_ATTEST_H
#define OSPI_BLOB_ATTEST_H

#include <stdint.h>

#define OSPI_BLOB_ADDR   0x90000000u
#define OSPI_BLOB_LEN    {len(blob)}u

// SHA-256 of the blob AS FLASHED. Compiled into the attested internal region;
// ospi_hash.c hashes [OSPI_BLOB_ADDR, +OSPI_BLOB_LEN) and compares.
static const uint8_t ospi_blob_sha256[32] = {{
{hexrows}
}};

#endif  // OSPI_BLOB_ATTEST_H
""", newline="\n")

    print(f"blob   : {blob_path}  ({len(blob):,} B, +{pad} pad)")
    print(f"header : {header}")
    print(f"sha256 : {digest.hex()}")
    print(f"\nFlash with (CubeProgrammer, external loader MX25LM51245G_STM32L562E-DK):")
    print(f"  STM32_Programmer_CLI -c port=SWD mode=UR -el MX25LM51245G_STM32L562E-DK \\")
    print(f"      -d {blob_path} 0x90000000 -v")
    return blob_path, header, digest


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: python -m offdevice.cnn_quant.model.blob_export <model.tflite>")
        raise SystemExit(2)
    export_blob(Path(sys.argv[1]))
