"""
mars_cnn_<mode>.keras + norm_stats.npz -> ONE C header the firmware #includes.

Emits the int8 flatbuffer, the z-score stats, and the I/O contract. The on-chip
frontend then does:
    features -> (x - mu) / sd -> clip(round(x / in_scale) + in_zero, -128, 127)
    -> int8 model -> (y - out_zero) * out_scale

TFLM parses the flatbuffer IN PLACE from flash, so the 16-byte alignment is
mandatory: 4-aligned works on x86 and hard-faults on the M33.
"""
import hashlib

import keras
import numpy as np
import tensorflow as tf

from pathlib import Path
from offdevice.cnn_quant.features import params
from offdevice.cnn_quant.paths import CSV, BINS
from offdevice.cnn_quant.model.dataset import build_dataset
from offdevice.cnn_quant.model.z_normal import apply_normalizer
from offdevice.cnn_quant.model.quantize import convert_int8
from offdevice.cnn_quant.model.svd_factor import factor_model

# ---- config -----------------------------------------------------------------
# "int8" = unfactored, or "svd_r<rank>" for the factored head (svd_factor.py sweeps).
EXPORT_MODEL = "svd_r16"

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE / "export"
HEADER = OUT_DIR / "mars_model_data.h"

# Where the model has to FIT (internal NS flash).
FLASH_FIT_BYTES = 256 * 1024


# ---- C formatting -----------------------------------------------------------
def c_bytes(data, per_line=12):
    """Rows of '0xNN,' -- same format as the existing generated headers."""
    lines = []
    for i in range(0, len(data), per_line):
        lines.append("  " + " ".join(f"0x{b:02x}," for b in data[i:i + per_line]))
    return "\n".join(lines)

def c_floats(arr, per_line=6):
    """Rows of float literals. %.9e keeps full float32 precision round-trip."""
    lines = []
    for i in range(0, len(arr), per_line):
        lines.append("  " + " ".join(f"{v:.9e}f," for v in arr[i:i + per_line]))
    return "\n".join(lines)


# ---- model selection + conversion --------------------------------------------
def build_tflite():
    """EXPORT_MODEL -> int8 flatbuffer bytes + the norm stats it pairs with.

    Converted fresh, so the calibration set, norm stats, and flatbuffer are one
    consistent generation."""
    base = keras.models.load_model(
        HERE / f"mars_cnn_{params.ACTIVE_MODE.lower()}.keras", compile=False)
    stats = np.load(HERE / "norm_stats.npz")
    x_train, _, _, _ = build_dataset(CSV, BINS)
    x_train = apply_normalizer(x_train, stats["mu"], stats["sd"])

    if EXPORT_MODEL == "int8":
        model = base
    elif EXPORT_MODEL.startswith("svd_r"):
        r = int(EXPORT_MODEL.removeprefix("svd_r"))
        model, _, _ = factor_model(base, r)
    else:
        raise SystemExit(f"unknown EXPORT_MODEL {EXPORT_MODEL!r} "
                         "(want 'int8' or 'svd_r<rank>')")
    return convert_int8(model, x_train), stats


def io_quant(tflite_bytes):
    """The int8 model's input/output (scale, zero_point) pairs.

    Read from the interpreter: the converter repicks them per
    calibration run, so every re-export can move them."""
    interp = tf.lite.Interpreter(model_content=bytes(tflite_bytes))
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]
    assert inp["dtype"] == np.int8 and out["dtype"] == np.int8, "model is not int8 I/O"
    return inp["quantization"], out["quantization"]


# ---- header emission ----------------------------------------------------------
def write_header(tflite_bytes, mu, sd, in_q, out_q, out_path):
    sha = hashlib.sha256(tflite_bytes).hexdigest()
    if tflite_bytes[4:8] != b"TFL3":
        raise SystemExit("conversion produced no TFL3 magic -- not a TFLite flatbuffer?")

    # mu/sd are saved shaped like a sample (40, N, 1); the firmware wants them
    # flat. Row-major => index = row * N_FEATURES + col, matching the assembled
    # image. Rows/cols are bins/features only under ASSEMBLY="stack".
    mu, sd = mu.ravel(), sd.ravel()
    n = params.N_BINS * params.N_FEATURES
    assert mu.size == n and sd.size == n, \
        f"norm stats are {mu.size} values, expected {n} -- stale norm_stats.npz?"

    (in_scale, in_zero), (out_scale, out_zero) = in_q, out_q

    with open(out_path, "w", newline="\n") as f:
        f.write(f"""// GENERATED by export.py - do not edit.
// model: {EXPORT_MODEL}  mode: {params.ACTIVE_MODE}  assembly: {params.ASSEMBLY}
// ({len(tflite_bytes)} bytes)
// sha256: {sha}
// Include from EXACTLY ONE translation unit -- these are definitions, not
// declarations; a second include duplicates every symbol at link time.
#ifndef MARS_MODEL_DATA_H
#define MARS_MODEL_DATA_H

#include <stdint.h>

#define MARS_N_BINS      {params.N_BINS}
#define MARS_N_FEATURES  {params.N_FEATURES}
#define MARS_N_INPUT     {n}
#define MARS_N_OUTPUT    2

// ---- int8 I/O contract ------------------------
// quantize   : q = clip(round(x / mars_in_scale) + mars_in_zero, -128, 127)
// dequantize : y = (q - mars_out_zero) * mars_out_scale
const float   mars_in_scale  = {in_scale:.9e}f;
const int32_t mars_in_zero   = {int(in_zero)};
const float   mars_out_scale = {out_scale:.9e}f;
const int32_t mars_out_zero  = {int(out_zero)};

// ---- z-score stats ------------------------
// The ({params.N_BINS}, {params.N_FEATURES}) image flattened row-major:
// index = row * MARS_N_FEATURES + col. Apply BEFORE quantizing:
// x_norm = (x - mu) / sd  -- the exact transform training saw. All 0/1 means
// the model trained on raw features and this is a no-op.
const float mars_norm_mu[MARS_N_INPUT] = {{
{c_floats(mu)}
}};

const float mars_norm_sd[MARS_N_INPUT] = {{
{c_floats(sd)}
}};

// ---- model ------------------------
// TFLM parses this IN PLACE from flash: the alignment is mandatory, not
// cosmetic (4-aligned works on x86, hard-faults on the M33).
#define MARS_MODEL_LEN {len(tflite_bytes)}

__attribute__((aligned(16)))
const unsigned char mars_model[] = {{
{c_bytes(tflite_bytes)}
}};

const unsigned int mars_model_len = MARS_MODEL_LEN;

#endif  // MARS_MODEL_DATA_H
""")
    return sha


# ---- run ----------------------------------------------------------------------
if __name__ == "__main__":
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    tflite_bytes, stats = build_tflite()
    in_q, out_q = io_quant(tflite_bytes)

    # keep the raw flatbuffer next to the header -- diffable, re-loadable
    tflite_path = OUT_DIR / f"mars_export_{EXPORT_MODEL}.tflite"
    tflite_path.write_bytes(tflite_bytes)

    sha = write_header(tflite_bytes, stats["mu"], stats["sd"], in_q, out_q, HEADER)

    size = len(tflite_bytes)
    fits = "fits" if size < FLASH_FIT_BYTES else "DOES NOT FIT"
    print(f"model   : {EXPORT_MODEL} ({params.ACTIVE_MODE})  {size:,} B  "
          f"sha256 {sha[:16]}...")
    print(f"flash   : {fits} {FLASH_FIT_BYTES // 1024} KB "
          f"({FLASH_FIT_BYTES - size:+,} B headroom)")
    print(f"input   : scale={in_q[0]:.9e}  zero={int(in_q[1])}")
    print(f"output  : scale={out_q[0]:.9e}  zero={int(out_q[1])}")
    print(f"wrote   : {HEADER}")
    print(f"          {tflite_path}")
