// GENERATED by blob_export.py - do not edit.
// Attestation for the OSPI XIP weight blob at 0x90000000.
// blob: grid_ae_int8.blob  (454432 bytes, 16-aligned)
#ifndef OSPI_BLOB_ATTEST_H
#define OSPI_BLOB_ATTEST_H

#include <stdint.h>

#define OSPI_BLOB_ADDR   0x90000000u
#define OSPI_BLOB_LEN    454432u

// SHA-256 of the blob AS FLASHED. Compiled into the attested internal region;
// ospi_hash.c hashes [OSPI_BLOB_ADDR, +OSPI_BLOB_LEN) and compares.
static const uint8_t ospi_blob_sha256[32] = {
  0xec, 0x5c, 0xe3, 0xf9, 0x34, 0x9e, 0x49, 0x81,
  0x9e, 0x8a, 0x60, 0x1e, 0xdc, 0x51, 0xfd, 0x9b,
  0x86, 0x4e, 0x37, 0xf0, 0xa2, 0xb0, 0x4d, 0xcb,
  0x8f, 0x58, 0xbf, 0xa5, 0x12, 0xed, 0xba, 0x41,
};

#endif  // OSPI_BLOB_ATTEST_H
