/*
 * ospi_hash.h -- attestation for the OSPI XIP weight blob (Secure).
 *
 * The model weights live in EXTERNAL OSPI flash (XIP at 0x90000000), OUTSIDE
 * the SHA-256-attested internal region. This check hashes the XIP-mapped blob
 * and compares it to the digest compiled into the internal image
 * (ospi_blob_attest.h, generated by offdevice/cnn_quant/model/blob_export.py).
 * An attacker who reflashes OSPI cannot match the digest without also tampering
 * the internal image (trips static_hash.c). Closes open-F (blob signing).
 *
 * Requires: OSPI already in memory-mapped read mode (OSPI_EnableMemoryMapped(0))
 * and the MPCWM watermark grown to span OSPI_BLOB_LEN (see MX_GTZC_S_Init).
 */
#ifndef OSPI_HASH_H
#define OSPI_HASH_H

/* Boot-time attestation of the OSPI blob. Prints OK / *** MISMATCH ***.
 * Returns 0 on match, -1 on mismatch or compute error. Non-destructive. */
int OspiHash_BootCheck(void);

#endif /* OSPI_HASH_H */
